apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - grafana-secret-sealed.yaml
  - dashboard-energy-configmap.yaml
  - grafana-timescaledb-secret-sealed.yaml
  - helmrelease.yaml

commonLabels:
  app: grafana
  version: base