app:
  title: Backstage
  baseUrl: https://backstage.k12n.com
  support:
    url: https://github.com/bokristoffersson/homelab-k12n-gitops

backend:
  baseUrl: https://backstage.k12n.com
  listen:
    port: 7007
  database:
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      database: ${POSTGRES_DB}
      ssl:
        require: false
  csp:
    connect-src: ["'self'", 'http:', 'https:']
    frame-ancestors: ["'self'"]

integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}

proxy:
  '/prometheus':
    target: 'http://prometheus.prometheus.svc.cluster.local:9090'
    allowedMethods: ['GET']
    headers:
      Authorization: 'Bearer ${PROMETHEUS_TOKEN}'

auth:
  environment: production
  providers:
    github:
      production:
        clientId: ${AUTH_GITHUB_CLIENT_ID}
        clientSecret: ${AUTH_GITHUB_CLIENT_SECRET}
        signIn:
          resolvers:
            - resolver: usernameMatchingUserEntityName

catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-catalog
  rules:
    - allow: [Component, System, API, Resource, Location]
  locations:
    - type: url
      target: https://github.com/bokristoffersson/homelab-k12n-gitops/blob/main/catalog/all.yaml

organization:
  name: Homelab

techdocs:
  builder: 'local'
  generator:
    runIn: 'local'
  publisher:
    type: 'local'








