apiVersion: v1
kind: Service
metadata:
  name: heatpump-web-leptos
  namespace: heatpump-web-leptos
  labels:
    app: heatpump-web-leptos
    backstage.io/kubernetes-id: heatpump-web-leptos
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: heatpump-web-leptos
