apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: backstage
resources:
  - namespace.yaml
  - ghcr-secret-sealed.yaml
  - database-secret-sealed.yaml
  - github-oauth-secret-sealed.yaml
  - database-init-job.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml








