apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

  # PostgreSQL database
  - postgres-pvc.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
  - postgres-backup-cronjob.yaml

  # Backstage application
  - serviceaccount.yaml
  - backstage-deployment.yaml
  - backstage-service.yaml

  # Sealed secrets
  - postgres-secret-sealed.yaml
  - postgres-backup-aws-secret-sealed.yaml
  - backstage-config-secret-sealed.yaml
