apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager
  - sealed-secrets
  # Temporarily commented out - will re-enable after sealed-secrets CRD is installed
  # - cloudflare-tunnel
  - redpanda-operator
  - traefik
  - traefik-config.yaml
