apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: heatpump-api
resources:
  - namespace.yaml
  - timescaledb-secret-sealed.yaml
  - ghcr-secret-sealed.yaml
  - deployment.yaml
  - service.yaml

