apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - jetstack.yaml
  - sealed-secrets.yaml
  - grafana.yaml
  - prometheus-community.yaml
  - longhorn.yaml
  - postgres-operator.yaml
  - redpanda.yaml
  - actions-runner-controller.yaml
  - kubernetes-mcp-server.yaml