apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - timescaledb-credentials-sealed.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - homelab-api-introspection-sealed.yaml

labels:
  - pairs:
      app: homelab-api
    includeSelectors: false
    includeTemplates: true
