apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - buildkit-rbac.yaml
  - controller-helmrelease.yaml
  - github-token-sealed.yaml
  - kubeconfig-sealed.yaml
  - namespace.yaml
  - runner-config.yaml
  - runner-helmrelease.yaml