apiVersion: cluster.redpanda.com/v1alpha2
kind: Topic
metadata:
  name: heatpump-settings
  namespace: redpanda-system
spec:
  kafkaApiSpec:
    brokers:
      - "redpanda-v2.redpanda-v2.svc.cluster.local:9092"
  partitions: 1
  replicationFactor: 1
  additionalConfig:
    retention.ms: "604800000"    # 7 days
    segment.ms: "3600000"        # 1 hour
