apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - heatpump-telemetry.yaml
  - heatpump-realtime.yaml
  - energy-realtime.yaml
  - sensor-state.yaml
  - heatpump-settings.yaml
