apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - grafana-secret-sealed.yaml
  - grafana-timescaledb-secret-sealed.yaml
  - grafana-prometheus-datasource.yaml
  - grafana-loki-datasource.yaml
  - datasource-generator-rbac.yaml
  - datasource-configmap-generator-job.yaml
  - helmrelease.yaml
