apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: timescaledb

resources:
  - ../../base/timescaledb

patches:
  - path: persistentvolumeclaim-patch.yaml
    target:
      kind: PersistentVolumeClaim
      name: timescaledb-data
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: timescaledb
