apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - namespace.yaml
  - slack-webhook-secret-sealed.yaml
  - serviceaccount.yaml
  - monitoring-script-configmap.yaml
  - cronjob.yaml
