---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: heatpump-settings-api-introspection
  namespace: heatpump-settings
spec:
  encryptedData:
    client-id: AgAR1RS5+61H832+n/aobgCzgbvC3wgO/onB3ZQ1q6W+i0lFHZJhOjbLcPXzk05P/A1wlmLlw8UI/6wKOvcVMA2YmYbjYB03ZmGPEugahK0tYZA3OG+arsIzFyepqQxBMjxiw/nujQeeHlRalKd9jJ5Rw+xmBfZ+TWD/bCpyOWmQHg2SXR1Y78rRn3MqLsucTXuY33xjF41oCdhR2emyU0SQkuzxpLZxt84h5E+IFCAl9zx5yFibzRGAoBJGLbM/ze1GyD6C/dHVVp2SJjJe7Sx53JMuHTO+7vruAHsZtqIRxPTzR7LotuOaOg0qIh8IAZRKSy8izSr8pTOxgGJTSPfQXmzC+V+FoRv5OPMudCL1n/YiyGt+eEfAsTGu1VkuZC1FbbzjVhNY77SCcsgJ91Iov0fsNMwjJtE94izV0wSVfP1B0B25uqEDn/UQNIKrds9pB69j9g6fNiUNE17Nyed8x0BQCnluSeWhWv+Ayu38YWiR+o2MaukmYuElz/OqrBL5axUgEsbTM6bRlv1994ddM4MyYFCqkcEA6KARMIlH7RpU1iLKW9Dv9kENHA/CVX8sozMpQQx/yc9PC7tjfY/dgKhafuo5g+k1EPJyq3MEfcb4BspiMuB9bErFk0DxaGpA7+XLd+e1hKLsCMkUXqPP+wErT+W62QZZdjCTXz7OSsOkL6GZevLnQ/ge8cWQKLi3BiFjo2NEfBkjNvZ7OxIzbHd0
    client-secret: AgBX4HcF9tGGXpirMRa8hP3wzEtKiqHlpnQIxtIuiGVdx8V1NV6GJ3DftZqcz/YxgYsy0xquBQ5zWFH7QGWYjnd+9SemvmRCCGHyuHdf3nmszVN/N8yPzozaOAW99qW8esJLO5mXNjXUGXO3yDqFc2INmAbzg2GhRgVKhzBXdxB3kSu6wQR+t/MB8637iHxZRg+1yK+2MSKIBJm5kdRlN6+hYPTXOb50QX8A1JT49IB8tY6Wha//Ydnd92LeSsvRLKuq7KhrW0jxVyNbq4GV/NN34LBAvENakpZJv1VxtxrfSRl5nOx3foNaosK2KxKMI3yWAHVzvDtgcHoC7pfiqEWyB61ZLpIIjW6wK/xYKbJ1vABNirbaHsxeiCeRQ1SBVujAH6JRtq6qTBqr3dSY8INWkVI6fjpy8/VvTWEoX0aqu70OcxJmuDQcoS41EiDTMDfTpOFOxaaTLOsCZm6s00HkFAzwrTJL4AS9d+8hqMDQKiSWwGpyMolTLDkLxMxZVA1tA4E1O0nVJO2b1pddg7qAY0NgD0QC/5xcCANY9Xl1dUydsTIXVFimDPC64+cMwIhjESOl7Nt8I6t+W0DJMOe1DwKVHDdtT+5JjB3Dx2UeGc9epH0MZ3Hms5+7DRfDvM7E3jSNEyi8tExTMHbUvln750WiIC7R+TSn6pFKXN6MplRGLzSwDOe1757vC28YNfXoe8hsaKelNK/q8r1BUzgZ
  template:
    metadata:
      name: heatpump-settings-api-introspection
      namespace: heatpump-settings
