site_name: Heatpump Settings Service
site_description: Service for managing heat pump configuration and settings

nav:
  - Overview: index.md
  - Redpanda Connect: redpanda-connect.md

theme:
  name: material
  palette:
    primary: orange
