site_name: 'Heatpump Web'
site_description: 'Heat pump dashboard web application'

nav:
  - Home: index.md
  - Architecture: architecture.md
  - Development: development.md
  - Deployment: deployment.md

plugins:
  - techdocs-core
