apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: heatpump-web
resources:
  - namespace.yaml
  - ghcr-secret-sealed.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml



