apiVersion: v1
kind: Service
metadata:
  name: heatpump-web
  namespace: heatpump-web
  labels:
    app: heatpump-web
    backstage.io/kubernetes-id: heatpump-web
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: heatpump-web



