apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - cloudflare-tunnel-secret-sealed.yaml
  - cloudflared-cert-secret-sealed.yaml
  - cloudflare-api-token-secret-sealed.yaml
  - deployment.yaml

commonLabels:
  app: cloudflare-tunnel