---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: oauth2-proxy-auth-claude-mcp
  namespace: traefik
spec:
  forwardAuth:
    address: http://oauth2-proxy-claude-mcp.oauth2-proxy.svc.cluster.local:4180/oauth2/claude/auth
    trustForwardHeader: true
    authRequestHeaders:
      - Cookie
      - X-Forwarded-Proto
      - X-Forwarded-Host
      - X-Forwarded-Uri
    authResponseHeaders:
      - X-Auth-Request-User
      - X-Auth-Request-Email
      - X-Auth-Request-Access-Token
      - Authorization
