---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik
resources:
  - forwardauth.yaml
  - traefikoidc.yaml
  - auth-errors.yaml
  - cors.yaml
  - headers.yaml
  - https-scheme.yaml
