apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mqtt-generator
resources:
  - ../../base/mqtt-generator

# Local development overrides
patches:
  # Use minimal resources for local testing
  - target:
      kind: Deployment
      name: mqtt-generator
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 10m
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 32Mi
