---
apiVersion: v1
kind: ConfigMap
metadata:
  name: blueprint-traefikoidc
  namespace: authentik
  labels:
    app.kubernetes.io/name: authentik-blueprints
data:
  traefikoidc.yaml: |
    version: 1
    metadata:
      name: traefikoidc
    entries:
      # OAuth2 Provider for traefikoidc Traefik plugin
      - model: authentik_providers_oauth2.oauth2provider
        identifiers:
          name: traefikoidc
        attrs:
          authorization_flow: !Find [authentik_flows.flow, [slug, default-provider-authorization-implicit-consent]]
          invalidation_flow: !Find [authentik_flows.flow, [slug, default-invalidation-flow]]
          client_type: confidential
          client_id: traefikoidc
          redirect_uris:
            - matching_mode: strict
              url: "https://api.k12n.com/oidc/callback"
            - matching_mode: strict
              url: "https://heatpump.k12n.com/oidc/callback"
          signing_key: !Find [authentik_crypto.certificatekeypair, [name, "authentik Self-signed Certificate"]]
          access_code_validity: minutes=1
          access_token_validity: hours=24
          refresh_token_validity: days=30
          issuer_mode: per_provider
          sub_mode: hashed_user_id
          include_claims_in_id_token: true
          property_mappings:
            - !Find [authentik_providers_oauth2.scopemapping, [scope_name, openid]]
            - !Find [authentik_providers_oauth2.scopemapping, [scope_name, email]]
            - !Find [authentik_providers_oauth2.scopemapping, [scope_name, profile]]

      # Application
      - model: authentik_core.application
        identifiers:
          slug: traefikoidc
        attrs:
          name: Traefik OIDC
          provider: !Find [authentik_providers_oauth2.oauth2provider, [name, traefikoidc]]
