---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: traefikoidc-client-secret
  namespace: authentik
spec:
  encryptedData:
    client-secret: AgA5dSFlUA/oGm6GLFwGCbYTuvf5utZXT84wRPf8HcqKLI2UD1YlTvBmCfLgrSz6x5Ise3FCzX+AIAbwajjA5/7kXCa6+YzbbmzhiJy1eDvtZG4hS263bIK7LJcI4XzS01slwKahF7WKxzrF+uvHFWINFVsvgk3LzjteQavuTAV2ObMa9ccMINNJKcfOYAR/6RgnCSZAgw3ZA/27209ztCwZAunLZXg5Eh0x0AbNCY/9eFa2qhkaD3qx0Lnng/J5s4NB5db51lPK6adADeWpYI9nmWkvLK9sacjI/sUF883LOnAwwrRjvhi3AAi4Dz7F4cfedQvhSB2Ps4NLeeGJaheGu7ePYgIYQMS+abSJ++3GxKhCHaoBI/KicbQ8NtI3VgzK9QategsTD8tghH/MLtw42chggwfbVzH3p2bf21wUe72/x3Op2PiDUI0PloGvShmWCVeYBkfUZ/URtyqprt1P4Xh02zhbQN2KqNKymP0tNo4QhkBXecBI8i+UM0kTOqaHoeUNrAz5c4d0LcO9ei2O2R74B58dc6VL07Y/Nk/HpRQMWLYYM3FBuvCbd15ZAVWnkyPtXOrbrLUI7+eD0yoYZjqRjhuyzxNDPERd1AwIi3qChDmDsjZbk1Q0e3GSiHs2t+nVSR9wLD2UgprDONV4HPcRgf4BUEv8j92WRuK6nDnobVfBdBJj5TG8zLlyjqtCwFRX6QDp2HUXt2KZ/e9dW/vcOXcwIUHO1pDUR4yxERTEPy7KE1WR+tRCfw==
  template:
    metadata:
      name: traefikoidc-client-secret
      namespace: authentik
