apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

  # Kong Gateway (DB-less mode)
  - config.yaml
  - deployment.yaml
  - service.yaml
  - oidc-secret-sealed.yaml
