---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt-input
  namespace: mqtt-input
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt-input
  template:
    metadata:
      labels:
        app: mqtt-input
    spec:
      containers:
        - name: app
          image: mqtt-input:latest
          imagePullPolicy: Never
          env:
            - name: APP_CONFIG
              value: /config/config.yaml
            - name: RUST_LOG
              value: info
            - name: REDPANDA_BROKERS
              value: "redpanda-v2-0.redpanda-v2.redpanda-v2.svc.cluster.local:9093"
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
      volumes:
        - name: config
          configMap:
            name: mqtt-input-config
            items:
              - key: config.yaml
                path: config.yaml

