---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik
resources:
  - api-routes.yaml
  - authentik-routes.yaml
  - backstage-routes.yaml
  - frontend-routes.yaml
  - mcp-routes.yaml
