apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mqtt-redpanda-bridge
resources:
  - namespace.yaml
  - deployment.yaml

configMapGenerator:
  - name: mqtt-redpanda-bridge-config
    files:
      - configs/energy.yaml
      - configs/temperature-indoor.yaml
      - configs/temperature-outdoor.yaml
      - configs/heatpump.yaml
